package org.epiclouds.dao.bean;

// Generated 2015-3-14 21:52:16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment implements java.io.Serializable {

	private Integer id;
	private Post post;
	private User user;
	private String content;
	private Date time;

	public Comment() {
	}

	public Comment(Post post, User user, String content, Date time) {
		this.post = post;
		this.user = user;
		this.content = content;
		this.time = time;
	}
	public Comment(int id,Post post, User user, String content, Date time) {
		this.id=id;
		this.post = post;
		this.user = user;
		this.content = content;
		this.time = time;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Post getPost() {
		return this.post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
