package org.epiclouds.dao.bean;

// Generated 2015-3-14 21:52:16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Post generated by hbm2java
 */
public class Post implements java.io.Serializable {

	private Integer id;
	private User user;
	private String content;
	private Date time;
	private int good;
	private Set comments = new HashSet(0);

	public Post() {
	}

	public Post(User user, String content, Date time, int good) {
		this.user = user;
		this.content = content;
		this.time = time;
		this.good = good;
	}

	public Post(int id,User user, String content, Date time, int good) {
		this.id=id;
		this.user = user;
		this.content = content;
		this.time = time;
		this.good = good;
	}
	public Post(User user, String content, Date time, int good, Set comments) {
		this.user = user;
		this.content = content;
		this.time = time;
		this.good = good;
		this.comments = comments;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public int getGood() {
		return this.good;
	}

	public void setGood(int good) {
		this.good = good;
	}

	public Set getComments() {
		return this.comments;
	}

	public void setComments(Set comments) {
		this.comments = comments;
	}

}
