package org.epiclouds.dao.bean;

// Generated 2015-3-14 21:52:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;
	private Set posts = new HashSet(0);
	private Set comments = new HashSet(0);

	public User() {
	}

	public User(String username, String password) {
		this.username = username;
		this.password = password;
	}
	public User(int id,String username, String password) {
		this.id=id;
		this.username = username;
		this.password = password;
	}

	public User(String username, String password, Set posts, Set comments) {
		this.username = username;
		this.password = password;
		this.posts = posts;
		this.comments = comments;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getPosts() {
		return this.posts;
	}

	public void setPosts(Set posts) {
		this.posts = posts;
	}

	public Set getComments() {
		return this.comments;
	}

	public void setComments(Set comments) {
		this.comments = comments;
	}

}
